import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Credits & licenses · OrPaynter Overlay' };

export default function Credits() {
  return <main className="min-h-screen bg-[#101923] text-[#c4d2df] p-6 md:p-16">
    <div className="max-w-3xl mx-auto space-y-8">
      <a className="text-[#d4af37]" href="/">← OrPaynter Overlay</a>
      <header><p className="text-sm tracking-widest text-[#d4af37]">ORPAYNTER, INC.</p><h1 className="text-3xl font-semibold mt-3">A connected world, built together.</h1><p className="mt-4">OrPaynter Overlay builds on the work of open-source contributors, public information providers, and the people who maintain them. Their credit stays visible as the platform evolves.</p></header>
      <section className="space-y-3"><h2 className="text-xl text-white">The globe foundation</h2><p><a className="text-[#d4af37] underline" href="https://github.com/simplifaisoul/osiris">OSIRIS by simplifaisoul and its contributors</a> supplied the original globe dashboard, source integrations, layer controls, and investigation interfaces. This fork starts at commit <code className="break-all">4ba7184ff31db06cb33c47de029c2d4255806458</code>. Copyright © 2026 simplifaisoul. Its MIT notice is retained in full.</p><p>OrPaynter adds company context, evidence capture, the existing Grok bridge, source integrity, recovery, and the Overlay experience. Original OrPaynter contributions are offered under MIT. The source has been prepared locally; no new public release is claimed here.</p></section>
      <section className="space-y-3"><h2 className="text-xl text-white">The shared software</h2><p><a className="underline" href="https://maplibre.org/">MapLibre contributors</a> power the map renderer. <a className="underline" href="https://github.com/shashwatak/satellite-js">satellite.js contributors</a> provide orbital propagation. Next.js, React, Lucide, Motion, and the other dependencies make the interface possible. Each dependency retains its own license; the vendored MapLibre notice remains intact.</p></section>
      <section className="space-y-3"><h2 className="text-xl text-white">The world information</h2><p>USGS, NOAA/NWS, public orbital-element providers, aviation and maritime sources, transport agencies, news organizations, and camera operators supply information under their own terms. The source links, receipt times, and uncertainty belong with the information.</p><p>The upstream public-webcam catalogue credits <a className="underline" href="https://www.bekijkhet.nu/">Bram and Annelies at bekijkhet.nu</a>, maintained since 2012. Original camera operators retain credit and control of their streams.</p><p>The existing Grok installation connects to an external model service. MCP can connect services and tools; neither connection changes their ownership or license. An open-source interface does not make every connected service or dataset open source.</p></section>
      <section className="space-y-3"><h2 className="text-xl text-white">Where Overlay goes next</h2><p>One navigable world with updating sources, saved evidence, clearly marked modeled possibilities, and actions routed through connected services. Updating and frozen source captures work today. Full globe history, isolated what-if worlds, shared spaces for other users, and a unified MCP connector registry remain the next implementation steps.</p><p>Private company records, credentials, saved jobs, and provider entitlements stay separate from the shared application source. AIA retains authority over consequential company execution.</p></section>
      <footer className="text-sm text-[#93a8bd]">Credit is part of provenance. OrPaynter Overlay is a derivative platform; upstream contributors do not endorse it.</footer>
    </div>
  </main>;
}
