import { describe,it,expect } from 'vitest';
import { collectSnapshot, normalizeFeed, validSnapshotId, analysisPrompt } from './observations';
import { requireLocalRequest } from './local-scope';
const raw=JSON.stringify({features:[{id:'usgs-test',geometry:{type:'Point',coordinates:[-97,32,8]},properties:{title:'M 2.6 Test',mag:2.6,time:Date.UTC(2026,8,29),url:'https://earthquake.usgs.gov/earthquakes/eventpage/test'}}]});
describe('public source capture',()=>{
 it('retains source identity, time and hash without inventing damage',()=>{const feed=normalizeFeed('usgs',JSON.parse(raw),raw,'2026-09-29T00:00:00Z');expect(feed.status).toBe('available');expect(feed.rawHash).toMatch(/^[a-f0-9]{64}$/);expect(feed.items[0].lat).toBe(32);expect(feed.items[0].reportedAt).toBe('2026-09-29T00:00:00.000Z');expect(feed.interpretation).toContain('no property damage');});
 it('unavailable source does not erase another source or fabricate records',async()=>{const snapshot=await collectSnapshot((async(url)=>{if(String(url).includes('weather.gov'))throw new Error('offline');return new Response(raw);}) as typeof fetch);expect(snapshot.feeds[0].status).toBe('available');expect(snapshot.feeds[1].status).toBe('unavailable');expect(snapshot.feeds[1].items).toEqual([]);expect(snapshot.id).toMatch(/^[a-f0-9]{64}$/);expect(analysisPrompt('Inspect',snapshot)).toContain('No records returned never proves no risk');});
 it('empty source response records unknown coverage',()=>{const feed=normalizeFeed('nws',{features:[]},'{"features":[]}','2026-09-29');expect(feed.status).toBe('empty');expect(feed.total).toBe(0);});
 it('malformed provider results are rejected',()=>expect(()=>normalizeFeed('usgs',{},'{}','now')).toThrow('feature list'));
 it('snapshot identifier rejects path traversal and arbitrary names',()=>{expect(validSnapshotId('../auth.json')).toBe(false);expect(validSnapshotId('a'.repeat(64))).toBe(true);expect(validSnapshotId('g'.repeat(64))).toBe(false);});
 it('record links cannot execute scripts and invalid coordinates remain unknown',()=>{const feed=normalizeFeed('usgs',{features:[{id:'x',geometry:{type:'Point',coordinates:[900,900]},properties:{url:'javascript:alert(1)'}}]},'{}','now');expect(feed.items[0].link).toBe(null);expect(feed.items[0].lat).toBe(null);});
 it('accepts Next normalized URL only when HTTP Host matches the local browser origin',()=>{expect(()=>requireLocalRequest(new Request('http://localhost:4180/api/orpaynter/grok',{headers:{host:'127.0.0.1:4180',origin:'http://127.0.0.1:4180'}}))).not.toThrow();for(const host of ['evil.example:4180','127.0.0.1:9999','localhost:4180@evil.example'])expect(()=>requireLocalRequest(new Request('http://localhost:4180/api/orpaynter/grok',{headers:{host,origin:'http://127.0.0.1:4180'}}))).toThrow();});
 it('only loopback and same-origin local runtime requests pass',()=>{expect(()=>requireLocalRequest(new Request('http://127.0.0.1:4180/api/orpaynter/grok',{headers:{origin:'http://127.0.0.1:4180'}}))).not.toThrow();expect(()=>requireLocalRequest(new Request('http://127.0.0.1:4180/api/orpaynter/grok',{headers:{origin:'https://other.example'}}))).toThrow();expect(()=>requireLocalRequest(new Request('https://public.example/api/orpaynter/grok'))).toThrow();});
});
