'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, BriefcaseBusiness, ChevronDown, ChevronUp, Radio, Bot } from 'lucide-react';
import type { OperatingProfile } from '@/lib/orpaynter/setup';
import type { MapRecoveryState } from '@/lib/orpaynter/map-recovery';
import type { CompanyState, CompanyWork } from '@/lib/orpaynter/company';
import { elapsed, receiptState, type FeedReceipt } from '@/lib/orpaynter/live';
type ContextRecord={title:string;url:string;summary:string;nextAction?:string;lastEdited:string;recordStatus?:string};
type Context={capturedAt?:string;sourceMode:string;records:ContextRecord[];controls:ContextRecord[]};
type Recovery={sources:{source:string;status:string;checkedAt:string;receivedAt:string|null;lastGoodHash:string|null;failures:number;attempts:number;nextRetryAt:string|null}[];events:{id:string;at:string;source:string;kind:string;detail:string}[]};
type Activity={supervisor?:{status:string;checkedAt:string;restartCount:number;events:{at:string;kind:string;detail:string}[]}|null;checkedAt:string;grok:{ready:boolean;version:string|null};jobs:{runId:string;status:string;objective:string;startedAt:string;companyWork?:CompanyWork}[];openclaw:{reachable:boolean};aia:{reachable:boolean;companyReadConnected:boolean}};
export default function CompanyOperatingDesk({revealed,receipts,selected,onSelect,mapRecovery,profile,onProfile}:{profile:OperatingProfile;onProfile:(profile:'company'|'world')=>void;mapRecovery:MapRecoveryState;revealed:boolean;receipts:Record<string,FeedReceipt>;selected:CompanyWork|null;onSelect:(work:CompanyWork)=>void}) {
 const [company,setCompany]=useState<CompanyState|null>(null),[context,setContext]=useState<Context|null>(null),[activity,setActivity]=useState<Activity|null>(null);
 const [recovery,setRecovery]=useState<Recovery|null>(null);
 const [tab,setTab]=useState<'work'|'workers'|'sources'|'healing'>('work'),[open,setOpen]=useState(true),[now,setNow]=useState(Date.now()),[error,setError]=useState('');
 useEffect(()=>{if(window.innerWidth<700)setOpen(false);let stopped=false;
  async function work(){if(document.hidden)return;try{const r=await fetch('/api/orpaynter/recovery?source=company',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(!stopped){const healthy=['healthy','recovered'].includes(d.recovery.status);setCompany(healthy?d.payload:null);setError(healthy?'':'Company source could not be verified. Automatic retry remains bounded.');}}catch{if(!stopped)setError('Company refresh unavailable; saved records may be old.');}}
  async function workers(){if(document.hidden)return;try{const r=await fetch('/api/orpaynter/activity',{cache:'no-store'});if(r.ok&&!stopped)setActivity(await r.json());}catch{/* Keep the last receipt timestamp visible. */}}
  async function healing(){if(document.hidden)return;try{const r=await fetch('/api/orpaynter/recovery',{cache:'no-store'});if(r.ok&&!stopped)setRecovery(await r.json());}catch{}}
  void work();void workers();void healing();fetch('/api/orpaynter/control',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!stopped)setContext(d);}).catch(()=>{});
  const a=setInterval(work,30000),b=setInterval(()=>{void workers();void healing();},5000),c=setInterval(()=>setNow(Date.now()),1000);
  const visible=()=>{if(!document.hidden){void work();void workers();}};document.addEventListener('visibilitychange',visible);
  return()=>{stopped=true;clearInterval(a);clearInterval(b);clearInterval(c);document.removeEventListener('visibilitychange',visible);};
 },[]);
 const work=[...(company?.work||[])].sort((a,b)=>Number(b.repo==='orpaynter/AIA'&&b.number===126)-Number(a.repo==='orpaynter/AIA'&&a.number===126)||Number(b.priority==='do-now')-Number(a.priority==='do-now')||b.updatedAt.localeCompare(a.updatedAt));
 const feedList=Object.values(receipts),failed=feedList.filter(r=>receiptState(r,now)==='unavailable'||receiptState(r,now)==='stale').length;
 if(!revealed)return null;
 return <section className={`orpa-desk ${open?'is-open':'is-closed'}`} aria-label="OrPaynter company operations" data-operating-profile={profile}>
  <button className="orpa-desk-title" aria-label={open?'Collapse company operations':'Open company operations'} onClick={()=>setOpen(!open)}><BriefcaseBusiness size={19}/><span><strong>OrPaynter, Inc.</strong><small>Oliver Paynter · sole operator</small></span>{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>
  {open&&<><div className="orpa-company-setup" role="group" aria-label="Operating view"><button aria-pressed={profile==='company'} onClick={()=>onProfile('company')}>Company operations</button><button aria-pressed={profile==='world'} onClick={()=>onProfile('world')}>World exploration</button><small>{profile==='custom'?'Custom layers · your selection is retained':profile==='company'?'Work, weather, assets and source receipts':'Global movements, orbits and infrastructure'}</small></div><nav aria-label="Company workspace tabs">{(['work','workers','sources','healing'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='work'?<BriefcaseBusiness size={13}/>:t==='workers'?<Bot size={13}/>:<Radio size={13}/>} {t}</button>)}</nav><div className="orpa-desk-body">
   {tab==='work'&&<><div className="orpa-desk-sync"><i className={company?.github.status==='connected'&&!error?'ok':''}/><strong>{company?.github.status==='connected'?'Owner account connected':company?'GitHub unavailable':'Connecting owner account…'}</strong><small>GitHub · {company?.checkedAt?elapsed(company.checkedAt,now):'first read pending'} · checks every 30s</small></div>
    {(error||company?.github.error)&&<p className="orpa-desk-warning">{error||company?.github.error}</p>}
    {context?.records?.length? <details className="orpa-company-context"><summary>Company focus & operating limits</summary><small>{context.sourceMode} · captured {context.capturedAt?new Date(context.capturedAt).toLocaleString():'time unknown'}</small>{context.records.map(r=><article key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title}<ArrowUpRight size={12}/></a><p>{r.summary}</p>{r.nextAction&&<p>{r.nextAction}</p>}<small>Edited {new Date(r.lastEdited).toLocaleDateString()} · {r.recordStatus}</small></article>)}<p>Company records guide priorities. GitHub labels do not authorize customer messages, collections or production changes.</p></details>:null}
    <div className="orpa-desk-count"><strong>{work.length} open work records</strong><small>AIA + ClaimFlow · repository scope</small></div>
    <p className="orpa-desk-hint">Choose real work for Grok to investigate.</p>
    {work.slice(0,20).map(w=><article className={`orpa-work-card ${selected?.id===w.id?'selected':''}`} key={w.id}><div><span>{w.repo.split('/')[1]} #{w.number}</span><b>{w.draft?'DRAFT':w.priority==='do-now'?'DO NOW':w.priority==='backlog'?'BACKLOG':w.kind==='pull_request'?'OPEN PR':'OPEN'}</b></div><button onClick={()=>onSelect(w)}>{w.title}</button><p>{w.assignees.length?`Assigned: ${w.assignees.join(', ')}`:'No assignee recorded'} · edited {new Date(w.updatedAt).toLocaleDateString()}</p><a href={w.url} target="_blank" rel="noreferrer">Source record <ArrowUpRight size={12}/></a></article>)}
    {work.length>20&&<p className="orpa-desk-hint">Showing the first 20, with World Twin and priority work first. {work.length-20} further records in the connected repositories.</p>}
    {!work.length&&company&&<p className="orpa-desk-hint">No work records available from this read. This does not establish an empty company queue.</p>}
   </>}
   {tab==='workers'&&<><div className="orpa-desk-sync"><strong>Actual process activity</strong><small>Local journal · {activity?.checkedAt?elapsed(activity.checkedAt,now):'pending'} · checks every 5s</small></div><div className="orpa-runtime-row"><b>Grok Bot</b><span>{activity?.grok.ready?'Ready for a job':'Sign-in status pending'}</span></div><div className="orpa-runtime-row"><b>OpenClaw</b><span>{activity?.openclaw.reachable?'Runtime reachable':'Runtime unavailable'}</span><small>Company job stream is not connected.</small></div><div className="orpa-runtime-row"><b>AIA / ClaimFlow</b><span>{activity?.aia.reachable?'Health endpoint reachable':'Local service unavailable'}</span><small>Company claims and execution are not connected.</small></div><p className="orpa-desk-hint">These are recorded Grok jobs, not a workforce count. Each job keeps its exact task and source snapshot.</p>{activity?.jobs.map(j=><article className="orpa-work-card" key={j.runId}><div><span>Grok · {j.runId.slice(0,8)}</span><b className={j.status==='running'?'running':''}>{j.status.toUpperCase()}</b></div><p>{j.companyWork?.title||j.objective}</p><small>Started {new Date(j.startedAt).toLocaleString()}</small></article>)}</>}
   {tab==='healing'&&<><div className="orpa-healing-note"><strong>Self-healing is active</strong>Failed reads retry within limits. Valid data remains visible with its original time. Bad replacements are rejected; repeated failures pause. Company approvals and measurements are never rewritten by recovery.</div><article className="orpa-feed-receipt"><div><strong>Globe renderer</strong><b data-state={mapRecovery.status}>{mapRecovery.status}</b></div><p>{mapRecovery.detail}</p><small>{mapRecovery.attempts} automatic rebuilds · {elapsed(mapRecovery.at,now)}</small></article><article className="orpa-feed-receipt"><div><strong>Local server</strong><b>{activity?.supervisor?.status||'supervisor not running'}</b></div><p>{activity?.supervisor?`${activity.supervisor.restartCount} restarts · checked ${elapsed(activity.supervisor.checkedAt,now)}`:'Server recovery requires the local supervisor launcher.'}</p></article>{recovery?.sources.map(r=><article className="orpa-feed-receipt" key={r.source}><div><strong>{r.source}</strong><b data-state={r.status}>{r.attempts?r.status:'not checked'}</b></div><p>Last valid input {elapsed(r.receivedAt,now)} · {r.failures} failed checks</p><code>{r.lastGoodHash?`SHA-256 ${r.lastGoodHash.slice(0,16)}`:'No valid saved input'}</code>{r.nextRetryAt&&<small>Next eligible check {new Date(r.nextRetryAt).toLocaleTimeString()}</small>}</article>)}<p className="orpa-desk-hint">Recovery journal</p>{recovery?.events.slice(0,12).map(e=><article className="orpa-work-card" key={e.id}><div><span>{e.source}</span><b>{e.kind}</b></div><p>{e.detail}</p><small>{new Date(e.at).toLocaleTimeString()}</small></article>)}<p className="orpa-desk-hint">Retries and recovered inputs are local operational proof. They do not establish improved AI judgment or an autonomous customer workforce.</p></>}
   {tab==='sources'&&<><div className="orpa-desk-sync"><strong>{failed?`${failed} feed checks need attention`:'Source receipts'}</strong><small>Refresh time describes receipt, not observation accuracy.</small></div>{feedList.map(r=><article className="orpa-feed-receipt" key={r.id}><div><strong>{r.name}</strong><b data-state={receiptState(r,now)}>{receiptState(r,now)}</b></div><p>{r.receivedAt?`Received ${elapsed(r.receivedAt,now)}`:'No successful receipt'} · {r.count===null?'count unknown':`${r.count.toLocaleString()} records`}</p><small>{r.mode==='model'?'Calculated from public orbital elements · checks every 30s':r.mode==='reference'?'Reference catalogue; camera availability varies':`Checks every ${r.cadenceMs/60000<1?'30 seconds':`${r.cadenceMs/60000} minutes`}`}{r.sourceAt?` · feed timestamp ${new Date(r.sourceAt).toLocaleTimeString()}`:' · feed timestamp unknown'}</small>{r.state==='empty'&&<small>Empty response does not prove no events or coverage.</small>}{r.state==='unavailable'&&<small>Latest fetch failed. Previously received markers may remain on the globe.</small>}</article>)}<p className="orpa-desk-hint">The satellite layer shows calculated positions. Imagery, camera streams, aircraft and vessels depend on their own providers. Unconnected layers do not become live by turning them on.</p></>}
  </div><footer>Owner workspace · AIA retains execution authority<br/><a href="/credits" target="_blank" rel="noreferrer">Built with open source · credits & licenses ↗</a></footer></>}
 </section>;
}
